### ISSUE TITLE
bios:366: [string "startup"]:2: '=' expected on boot

### ISSUE THREAD

**Issue by dezzak** [dopscraft/core#3]
As per the subject, I did the following on a new box:

```
githubinstall core core
core/setup/setup
reboot
```

Get the following after reboot:

```
CraftOS 1.6
bios:366: [string "startup"]:2: '=' expected on boot
>
```

seems to function though

**Comment by ghost** [comment]
Fixed with commit 71041f6c5a5e8061275fc9df97d02d9e5173196e
